env:
  global:
    - PATH=$HOME/.local/bin:$PATH

cache:
  directories:
    - data

install:
  - pip install --user awscli
  - wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.tar.gz
  - tar xzvf hugo_0.48_Linux-64bit.tar.gz
  - mv hugo ~/.local/bin/
  - wget https://github.com/mikefarah/yq/releases/download/2.1.1/yq_linux_amd64 -O ~/.local/bin/
  - chmod o+x ~/.local/bin/yq

script: ./build.sh

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    local_dir: public/
    bucket: "ops.laps.run"
    skip_cleanup: true
    on:
      repo: lapsrun/ops.laps.run
      branch: master
