baseURL = "https://ops.laps.run/"
languageCode = "en-us"
title = "laps.run ops panel"

[taxonomies]
  tag = "tags"

[params]
    Title = "laps.run ops panel"
    site_description = "Operations Visibility Panel for https://laps.run. Data on builds, preview deploys, and production deploys"
    # twitter_handle = "laps_run"
    github_repo = "https://github.com/lapsrun/ops.laps.run/"

[mediaTypes]
  [mediaTypes."text/csv"]
    suffixes = ["csv"]

[outputs]
  section = ["HTML", "RSS", "CSV"]
